GraphAr parser
TuGraph-family/tugraph-db pull request #277
Opened 2023-08-15 03:31 UTC by jasinliu

To support GraphAr graph data import.

1. support vertex column parser.

2023-08-31 08:44 UTC, qishipengqsp requested changes
其他整体问题：
1. 添加注释
2. 补充相应的Unit Test和Integrate Test

2023-08-31 08:44 UTC, qishipengqsp commented on src/import/import_config_parser.h
从graphAr的yaml到conf的这个转换逻辑在哪里？

2023-08-31 08:44 UTC, qishipengqsp commented on src/import/column_parser.h
这个文件给拆开吧，现在太多parser了。把BlockParser ColumnParser JsonLineParser和GraphArParser放到不同的文件中去

2023-08-31 08:44 UTC, qishipengqsp commented on src/import/column_parser.h
> +            break;
这里不需要break，上面有了return

2023-08-31 08:44 UTC, qishipengqsp commented on src/import/column_parser.h
> +            return FieldData(vertex.property<std::string>(prop).value());
这里是拷贝构造，需要换成没有拷贝的写法，你可以详细看一下parse_jsonline这个函数里面的实现，每个fieldData的构造都是zeroCopy的

2023-08-31 08:44 UTC, qishipengqsp commented on src/import/column_parser.h
> +            return FieldData(edge.property<std::string>(prop).value());
同上

2023-08-31 08:44 UTC, qishipengqsp commented on src/import/column_parser.h
> +            break;
同上

2023-08-31 08:44 UTC, qishipengqsp commented on src/import/column_parser.h
> +    FieldData ParseEdgeData(GAR_NAMESPACE::Edge edge, const std::string& prop,
GAR_NAMESPACE::Edge&

参数尽量设计成为引用，否则传参的时候存在拷贝

2023-08-31 08:44 UTC, qishipengqsp commented on src/import/column_parser.h
> +    GraphArParser(CsvDesc cd) : cd_(cd) {}
CsvDesc& cd

2023-08-31 08:44 UTC, qishipengqsp commented on src/import/import_v3.cpp
graphAr这个importor，感觉还是单独拆出来一个target比较好：
1. 代码逻辑干净，后续好迭代
2. 可以根据情况enable或者disable，graphAr的相关依赖还挺大的

2023-08-31 09:35 UTC, jasinliu commented on CMakeLists.txt
> +cmake_minimum_required(VERSION 3.16)
arrow 这个[pr](https://github.com/TuGraph-contrib/data-migration/pull/3)有说

2023-08-31 09:36 UTC, jasinliu commented on CMakeLists.txt
> +add_definitions(-DGAR_NAMESPACE=GraphArchive)
ok 这样可以把代码中的所有这个命名空间改成GraphAr了

2023-08-31 09:53 UTC, jasinliu commented on src/import/column_parser.h
> +    GAR_NAMESPACE::Property get_primary_key(const GraphArchive::VertexInfo& ver_info) {
是一个可自定义配置的namespace 默认值是GraphArchive

2023-08-31 09:56 UTC, jasinliu commented on src/import/column_parser.h
ok

2023-08-31 09:56 UTC, jasinliu commented on src/import/import_config_parser.h
todo

2023-08-31 09:59 UTC, jasinliu commented on src/import/column_parser.h
> +            return FieldData(vertex.property<std::string>(prop).value());
get it

2023-09-11 09:40 UTC, qishipengqsp commented on ci/images/tugraph-compile-centos7-Dockerfile
现在dockerfile已经改过了，这就不改了

2023-09-11 09:40 UTC, qishipengqsp commented on ci/images/tugraph-compile-centos8-Dockerfile
现在dockerfile已经改过了，这就不改了

2023-09-11 09:40 UTC, qishipengqsp commented on ci/images/tugraph-compile-ubuntu18.04-Dockerfile
现在dockerfile已经改过了，这就不改了

2023-09-20 12:52 UTC, qishipengqsp commented on test/test_import_gar.cpp
> +    UT_LOG() << "Read gar datas";
data  没有datas

2023-09-20 12:52 UTC, qishipengqsp commented on test/test_import_gar.cpp
> +    UT_EXPECT_NO_THROW(ParserGraphArConf(conf, config.config_file));
这里还要校验一下conf的内容

2023-09-20 12:52 UTC, qishipengqsp commented on test/test_import_gar.cpp
> +    UT_EXPECT_NO_THROW(parser.ReadBlock(block));
还要想办法校验一下readBlock的内容对不对

2023-09-25 12:09 UTC, qishipengqsp reviewed
另外检查一下你所有的auto，auto是调用copy constructor的，尽量用auto&

2023-09-26 02:24 UTC, jasinliu commented on src/import/graphar_config.h
> +        gar_conf["schema"].push_back(schema_node);
暂不支持

2023-09-26 02:25 UTC, jasinliu commented on src/import/graphar_config.h
> +    CheckAdjListType(edge_info, adj_list_type);
这里gar设计有bug，先这样顶着

2023-09-26 08:33 UTC, jasinliu commented on src/import/graphar_parser.h
> +            // todo
Done

2023-09-26 11:46 UTC, jasinliu commented on src/import/graphar_parser.h
> +                    temp_vf.emplace_back(fd);
get it

2023-09-26 11:46 UTC, jasinliu commented on src/import/graphar_parser.h
> +                buf.emplace_back(temp_vf);
get it

2023-09-27 02:11 UTC, jasinliu commented on src/import/graphar_parser.h
> +    FieldData ParseEdgeData(GraphArchive::Edge& edge, const std::string& prop,
这两个没有共同的基类

2023-09-27 02:16 UTC, jasinliu commented on test/integration/test_import_gar.py
> +        assert vertex_res[0]['count(p)'] == 903
2. （3）需要测试相同edge label不同顶点的edge是否能解析，能删除的很少，感觉可以保留snb数据配置的完整性

2023-11-22 13:24 UTC, knightast commented on src/import/graphar_config.h
> +                FMA_LOG() << "Same edge label has different properties." << path;
FMA_ERR

2023-11-22 13:24 UTC, knightast commented on src/import/graphar_parser.cpp
> +        FMA_LOG() << "The primary key of " << ver_label << " isn't found!";
FMA_LOG 仅开发测试用

正式的代码里用 FMA_DEBUG / FMA_WARN / FMA_ERR

2023-11-22 13:24 UTC, knightast commented on src/import/graphar_parser.cpp
> +        throw std::runtime_error("the primary key of [" + ver_label + "] isn't found!");
throw InputError(...)

2023-11-22 13:24 UTC, knightast commented on test/resource/data/gar_test/edge_test/movie.graph.yml
> +version: gar/v1
movie.vertex.yml是空文件没问题？

2024-01-15 10:21 UTC, jasinliu commented on src/import/graphar_config.h
> +    default:
暂时不支持，先打印报错

2024-01-31 04:26 UTC, jasinliu commented
It is ready for review.😀 @qishipengqsp @acezen

2024-06-25 05:50 UTC, qishipengqsp approved these changes

2024-06-25 14:19 UTC, closed without merging