basic function for spatial
TuGraph-family/tugraph-db pull request #280
Opened 2023-08-22 06:54 UTC by hanwen-sun

1. 增添spatial.h和spatial.cpp文件，实现基础的spatial数据的定义。
2. 增添对应的test文件。
3. 在lgraph_type中添加spatial, 增添test_data_type对应模块。
4. 涉及switch(type) case Spatial的文件部分尚未实现。

TODO:
1. 完成上述第4条，完成spatial数据的schema定义
2. 完善test_data_convert, test_schema_change等对应测试文件。

2023-09-07 12:20 UTC, qishipengqsp requested changes
总的来说几个问题吧：
1. 抽象的问题，comments提到了，这个可能结合需求设计我们需要再讨论一下
2. test文件我都没看，等这波改完再看
3. import相关的你当前可以不改，先focus到schema和存储层上来
4. 代码风格的问题：驼峰or蛇形、class名大写or小写

2023-09-07 12:20 UTC, qishipengqsp commented on src/core/lgraph_spatial.cpp
> +void EndianTansfer(std::string& input) {
以及现在写的逻辑有2个问题
1. 可能越界
2. output.size == input.size - 2 ?

2023-09-07 12:20 UTC, qishipengqsp commented on src/core/lgraph_spatial.cpp
> +    EWKB[endian ? 8 : 9] = '2';
这个 赋值又是啥意思？看不太懂，感觉可能需要讲一下EWKB的layout和处理逻辑？

2023-09-07 12:20 UTC, qishipengqsp commented on src/core/schema.cpp
> +                throw InputError("invalid srid!\n");
如果要是封装了point，这里会简单点

2023-09-07 12:20 UTC, qishipengqsp commented on src/core/value.h
> +     *
不需要改这个

2023-09-07 12:20 UTC, qishipengqsp commented on src/core/value.h
> +// 这里需要先进行正确性判断吗?
你的spatial的类型都加一个对应的构造函数，传入char\*和size_t的构造函数就可以了，里面是给EWKB的，比如大概这么个写法：
str::string tmp = std::string((char*)p, s);
if(TryDecodeXXX(tmp)) {
    EWKB = std::move(tmp);
}

2023-09-07 12:20 UTC, qishipengqsp commented on src/restful/server/json_convert.h
> +    case FieldType::POINT:
这个json还是挺好支持的话，主要是human readable就行

2023-09-07 12:20 UTC, qishipengqsp commented on src/server/json_convert.h
> +                    return json(data.AsWsgLineString().AsEWKB());
json的目标是human readable的，所以这里建议给spatial的type都加一个ToString的方法，参考上面的date datetime

2023-09-07 12:20 UTC, qishipengqsp commented on src/server/proto_convert.h
> +        case FieldType::POINT:
这个要对应着修改proto了，并且需要实现一下

2023-09-07 12:20 UTC, qishipengqsp commented on test/test_data_type.cpp
这个文件等这波改完了我再看吧

2023-09-07 12:20 UTC, qishipengqsp commented on test/test_field_data_helper.cpp
这个文件等这波改完了我再看吧

2023-09-07 12:20 UTC, qishipengqsp commented on test/test_field_extractor.cpp
这个文件等这波改完了我再看吧

2023-09-07 12:20 UTC, qishipengqsp commented on test/test_lgraph_spatial.cpp
这个文件等这波改完了我再看吧

2023-09-10 09:09 UTC, hanwen-sun commented on test/test_cypher.cpp
> +        // {"RETURN point_ewkb("") as p1", 1},
这里之前想实现point_wkb, point_wkt的封装，支持用wkb和wkt格式创建point, 现在已经都实现。

2023-09-10 09:18 UTC, hanwen-sun commented on include/lgraph/lgraph_types.h
> +        <::lgraph_api::Wsg84>(*data.buf);
这里确实可能出问题，我添加一下对应的测试代码然后添加一下SRID_Type相关的检查与异常处理。

2023-09-10 09:21 UTC, hanwen-sun commented on include/lgraph/lgraph_types.h
> +        return "SPATIAL";
spatial类型是包含所有其他的空间数据类型，目前没有单独用到spatial类型的地方，但写空间数据查询的封装时可能会用到，所以我暂时没有把它删除。如果确实不会用到会删除spatial类型。

2023-09-10 09:24 UTC, hanwen-sun commented on src/core/field_data_helper.h
> +    50,  // point
这里的完整的EWKB模式需要存50byte, 可以压缩到39byte, 但是WKB/EWKB格式中一个坐标表示需要16byte，这里我不确定怎么压缩。所有数据都为16进制，可能整体都可以不存为string类型，这里需要讨论一下。

2023-09-10 09:26 UTC, hanwen-sun commented on src/core/field_data_helper.h
> +    50,  // point
以一个point类型为例： point(1.0 2.0) 01 0100 0020 E6100000 000000000000F03F 000000000000F03F 
可以轻松压缩为: 01 2 E610 16byte 16byte  共39位;

2023-09-10 10:47 UTC, hanwen-sun commented on src/core/field_data_helper.h
> +            switch (s) {     // 这里是否要加ewkb, 写法有待确认;
这里原来想的是有没有必要写一个std::string ewkb, 还是直接用v.AsString，现在去掉了，就这么写吧

2023-09-10 13:42 UTC, hanwen-sun commented on src/core/lgraph_spatial.cpp
> +void EndianTansfer(std::string& input) {
这里因为EWKB为十六进制表示, 十六进制的一个数字为4bit, 2 ^ 4, 所以每两个数字为1byte, little endian与big endian是每个byte相反表示, 所以对于某一big endian的16进制表示: 0x000010E6 其 little endian表示为 0xE6100000。我这里加个注释吧, 这段代码是把给定的字符串以step=2前后倒转，size不变。越界这里在什么情况下可能发生?没有想到越界的case.

2023-09-10 13:43 UTC, hanwen-sun commented on src/core/lgraph_spatial.cpp
> +bool TryDecodeEWKB(const std::string& EWKB, SpatialType type) {
已添加关于EWKB与WKB相关layout与转换的注释

2023-09-10 13:53 UTC, hanwen-sun commented on src/core/lgraph_spatial.cpp
> +void EndianTansfer(std::string& input) {
这里我添加一些big endian的WKB与EWKB构造格式的测试代码。

2023-09-11 01:06 UTC, hanwen-sun commented on src/server/proto_convert.h
> +        case FieldType::POINT:
这个proto_convert具体是做什么的?没太看懂，暂时不修改。

2023-09-21 14:37 UTC, knightast commented on include/lgraph/lgraph_spatial.h
> + * TODO:
用标准的TODO写法，注释中避免中文

2023-09-21 14:37 UTC, knightast commented on include/lgraph/lgraph_spatial.h
> +typedef bg::cs::geographic<bg::degree> Wgs84;
Wgs84 是什么意思

2023-09-21 14:37 UTC, knightast commented on include/lgraph/lgraph_spatial.h
> +typedef std::vector<boost::uint8_t> byte_vector;
数据类型统一格式

2023-09-21 14:37 UTC, knightast commented on include/lgraph/lgraph_spatial.h
> +    std::unique_ptr<Point<SRID_Type>> Point_;
注意参数命名规范

2023-09-21 14:37 UTC, knightast commented on include/lgraph/lgraph_types.h
> +    return FieldData(p); }
缩进

2023-09-21 14:37 UTC, knightast commented on include/lgraph/lgraph_types.h
> +        case FieldType::POLYGONCARTESIAN:
这个增加的数据类型感觉有多，为啥需要同时支持 WGS84、CARTESIAN、以及能不能用UNION包掉

2023-09-21 14:37 UTC, knightast commented on include/lgraph/lgraph_types.h
> +            case FieldType::SPATIAL:
支持的操作都有哪些？加减？

2023-09-21 14:44 UTC, qishipengqsp commented on include/lgraph/lgraph_spatial.h
> +typedef bg::cs::geographic<bg::degree> Wgs84;
应该是 Wsg84，一种坐标系。 这是一个typo

2023-09-21 14:45 UTC, qishipengqsp commented on include/lgraph/lgraph_types.h
> +        case FieldType::POLYGONCARTESIAN:
不太适合用union包掉，这个坐标系预期是向上透出暴露给用户

2023-09-22 02:03 UTC, hanwen-sun commented on test/test_field_data_helper.cpp
> +    for (int ft = (int)FieldType::NUL; ft <= (int)FieldType::POLYGONCARTESIAN; ft++) {
有必要吧, 现在blob是11, 后面又加了六种type, 不改没法测试六种spatial type.

2023-09-22 03:55 UTC, hanwen-sun commented on include/lgraph/lgraph_types.h
> +            case FieldType::SPATIAL:
目前只支持==, 空间数据不太好进行比较，加减运算等, 我调研别的数据库也没实现这些功能。空间数据更多是空间查询相关的操作，如distance(point1, point2), disjoint(geo1, geo2)等，会封装成built-in function;

2023-09-22 04:19 UTC, hanwen-sun commented on include/lgraph/lgraph_spatial.h
> +    std::unique_ptr<Point<SRID_Type>> Point_;
这里应该怎么命名合适?

2023-09-22 04:19 UTC, hanwen-sun commented on include/lgraph/lgraph_spatial.h
> + * TODO:
已修改

2023-09-22 04:19 UTC, hanwen-sun commented on include/lgraph/lgraph_spatial.h
> +typedef std::vector<boost::uint8_t> byte_vector;
已修改

2023-09-22 04:19 UTC, hanwen-sun commented on include/lgraph/lgraph_types.h
> +    return FieldData(p); }
已修改

2023-10-18 15:44 UTC, qishipengqsp commented on src/core/data_type.h
> +// #include "lgraph/lgraph_spatial.h"
这个不要留

2023-10-18 15:44 UTC, qishipengqsp commented on src/core/field_data_helper.h
> +             // 怎么处理?
这里？

2023-10-18 15:44 UTC, qishipengqsp commented on src/core/field_data_helper.h
> +            switch (s) {     // 这里是否要加ewkb, 写法有待确认;
这里？

2023-10-18 15:44 UTC, qishipengqsp commented on test/test_lgraph_spatial.cpp
> +    // 这里的primary_key不能相同;
注释要用英文，检查一下其他的注释吧

2023-10-18 15:44 UTC, qishipengqsp commented on test/test_lgraph_spatial.cpp
> +        UT_EXPECT_ANY_THROW(txn.AddVertex(
？

2023-10-18 15:44 UTC, qishipengqsp commented on src/import/column_parser.h
> +                    // TODO(shw): Support import for point type;
留个issue吧，怕忘了

2023-10-18 15:44 UTC, qishipengqsp commented on test/test_data_type.cpp
明天当面过一下ut的设计吧

2023-10-20 01:41 UTC, hanwen-sun commented on src/server/proto_convert.h
> +            // TODO(shw): 这里有必要在spatial中实现std::string&& 移动语义吗
这里为什么要销毁原有的str对象?

2023-10-24 09:15 UTC, hanwen-sun commented on test/test_lgraph_spatial.cpp
> +        UT_EXPECT_ANY_THROW(txn.AddVertex(
这里是测是否会抛出异常

2023-10-24 09:16 UTC, hanwen-sun commented on src/core/field_data_helper.h
> +// 这里有template的问题;
这里我还是留着, 之前总结了文档发钉钉了，要先删除吗?

2023-11-19 07:36 UTC, qishipengqsp commented on src/restful/server/rest_server.cpp
> +        // TODO(shw): string(_TU(Point(data.point()).ToString()));
这个todo是？

2023-11-19 07:36 UTC, qishipengqsp commented on test/test_proto_convert.cpp
> +        }
其他的类型也需要测试一下？

2023-11-19 07:36 UTC, qishipengqsp commented on test/test_lgraph_spatial.cpp
> +    UT_LOG() << "testing add";
大小写和上下的对齐吧

2023-11-19 07:36 UTC, qishipengqsp commented on test/test_lgraph_spatial.cpp
> +static void TestSampleDB(const std::string& dir, bool detach_property) {
这个函数名起的不太好，要不直接挪到下面的test case里面去？

2023-11-19 07:36 UTC, qishipengqsp commented on test/test_data_type.cpp
> +
其他的类型的还是尽量覆盖一下

2023-11-19 07:36 UTC, qishipengqsp commented on test/test_field_extractor.cpp
> +        CheckParseDataType<lgraph::PointWgs84>(FieldType::POINT, value_tmp,
应该还有另一个坐标系的覆盖一下

2023-11-20 09:25 UTC, hanwen-sun commented on src/core/lgraph_spatial.cpp
> +        // 如果WKT格式错误，这里会抛出异常; boost::exception_detail;
已修改

2023-11-20 09:52 UTC, hanwen-sun commented on src/restful/server/rest_server.cpp
> +        // TODO(shw): string(_TU(Point(data.point()).ToString()));
这里更可读的方式是先转换为spatial的类型，再调用string转换为string类型返回，参考上面的datetime

2023-11-20 11:26 UTC, hanwen-sun commented on src/restful/server/rest_server.cpp
> +        // TODO(shw): string(_TU(Point(data.point()).ToString()));
但是这么写会麻烦不少，需要调lgraph_api::point<coordinate>, 目前先留个TODO

2023-11-22 11:49 UTC, hanwen-sun commented on test/test_data_type.cpp
> +
已尽量覆盖

2023-11-22 12:00 UTC, hanwen-sun commented on test/test_field_extractor.cpp
> +        CheckParseDataType<lgraph::PointWgs84>(FieldType::POINT, value_tmp,
已覆盖

2023-11-22 12:12 UTC, hanwen-sun commented on test/test_lgraph_spatial.cpp
> +static void TestSampleDB(const std::string& dir, bool detach_property) {
改成TestErrorSchema可以吗

2023-11-22 12:14 UTC, hanwen-sun commented on test/test_lgraph_spatial.cpp
> +static void TestSampleDB(const std::string& dir, bool detach_property) {
改成TestWrongSchema可以吗

2023-11-22 12:26 UTC, hanwen-sun commented on test/test_proto_convert.cpp
> +        }
已添加

2023-11-22 12:35 UTC, hanwen-sun commented on test/test_lgraph_spatial.cpp
> +    UT_LOG() << "testing add";
已修改

2023-11-27 15:08 UTC, qishipengqsp approved these changes

2023-11-27 15:08 UTC, merged