change audit log file format into json
TuGraph-family/tugraph-db pull request #349
Opened 2023-12-25 01:58 UTC by SonglinLyu

change the original binary format of audit log file into readable human json format.

2024-01-08 15:07 UTC, qishipengqsp requested changes

2024-01-08 15:07 UTC, qishipengqsp commented on include/tools/lgraph_log.h
> +    void Init(std::string log_dir = "logs/") {
没有判断log_dir.empty()的情况？

2024-01-08 15:07 UTC, qishipengqsp commented on include/tools/lgraph_log.h
> +    void Init(std::string log_dir = "logs/") {
写的时候看一下前面的log manager吧

2024-01-08 15:07 UTC, qishipengqsp commented
ut不需要修改？

2024-01-11 09:13 UTC, knightast commented on src/core/audit_logger.h
> +        LOG_DEBUG() << "[AUDIT TEST]" << log_line;
AUDIT TEST?

2024-01-11 09:13 UTC, knightast commented on src/core/audit_logger.h
> +    inline bool ParseAuditLog(std::string path, std::string& log_line, lgraph::LogMessage& msg) {
有对应的UT来测试么

2024-01-13 23:19 UTC, SonglinLyu commented on include/tools/lgraph_log.h
> +BOOST_LOG_ATTRIBUTE_KEYWORD(log_type_attr, "LogType", std::string)
改成了 调试信息会在存储过程运行结束后合并为一条WARN等级的日志条目输出至日志文件中。

2024-01-13 23:30 UTC, SonglinLyu commented on docs/zh-CN/source/5.developer-manual/5.ecosystem-tools/4.log.md
> +请使用python自带的print输出调试信息，调试信息会在存储过程运行结束后统一输出至日志文件中，形成一条级别为`WARN`的日志。
改成了 调试信息会在存储过程运行结束后合并为一条WARN等级的日志条目输出至日志文件中。

2024-01-14 02:37 UTC, SonglinLyu commented on include/tools/lgraph_log.h
> +            keywords::file_name = log_dir_ + "%Y%m%d_%H%M%S",
这个文件名主要是为了和以前的代码兼容，以前的auditlog文件名就是这种格式，日期检索的时候用的

2024-01-14 02:45 UTC, SonglinLyu commented on include/tools/lgraph_log.h
> +    void Init(std::string log_dir = "logs/") {
> 没有判断log_dir.empty()的情况？

这部分逻辑原来放在lgraph_server.cpp里了，在167行

2024-01-14 02:47 UTC, SonglinLyu commented on src/core/audit_logger.h
> +        // file_.Write(msg.SerializeAsString().c_str(), len);
这是原来版本的写入日志的代码，之前不确定留不留，我现在删了

2024-01-14 02:48 UTC, SonglinLyu commented on src/core/audit_logger.h
> +        LOG_DEBUG() << "[AUDIT TEST]" << log_line;
测试用的，忘删了，现在就删

2024-01-14 02:50 UTC, SonglinLyu commented on src/core/audit_logger.h
> +    inline bool ParseAuditLog(std::string path, std::string& log_line, lgraph::LogMessage& msg) {
我看原本的ut测试就直接测了读出来的东西放到lgraph::LogMessage& msg里之后是不是一致的，所以就没单独写一个测试

2024-01-14 02:51 UTC, SonglinLyu commented
> ut不需要修改？

原本的ut测试里测了读出来的东西放到lgraph::LogMessage& msg里之后是不是一致的，还需要再加一个比如说验证json文件里的文本内容是否正确的测试吗？

2024-01-15 00:15 UTC, SonglinLyu commented on docs/zh-CN/source/5.developer-manual/5.ecosystem-tools/4.log.md
> +请使用2.2中提供的log宏输出调试信息，避免使用cout或者printf等输出方式。
加了一段示例，代码放在procedures/demo里了，如果不需要保留的话我可以删掉

2024-01-15 03:33 UTC, qishipengqsp requested changes

2024-01-20 05:52 UTC, qishipengqsp approved these changes

2024-01-20 05:52 UTC, merged