support spatial function
TuGraph-family/tugraph-db pull request #378
Opened 2024-01-14 12:49 UTC by hanwen-sun

2024-02-01 13:03 UTC, qishipengqsp requested changes

2024-02-01 13:03 UTC, qishipengqsp commented on src/cypher/filter/filter.h
> +                case FieldType::POINT: {
缩进

2024-02-01 13:03 UTC, qishipengqsp commented on src/cypher/procedure/procedure.cpp
> +        "wrong arguments number");
换行？

2024-02-06 11:35 UTC, hanwen-sun commented on include/lgraph/lgraph_spatial.h
> +    double Distance(LineString<SRID_Type>& other);
这里目前不太行，因为每个子类中的spatialtype是不同的，调用distance时会根据传入的type数据与实际持有的数据进行计算。如果想要加到spatialbase中需要进行重构，让spatialbase持有实际的空间数据。

2024-02-06 11:35 UTC, hanwen-sun commented on include/lgraph/lgraph_spatial.h
> +    double Distance(LineString<SRID_Type>& other);
> 这几个函数加到基类SpatialBase里面去？

这里目前不太行，因为每个子类中的spatialtype是不同的，调用distance时会根据传入的type数据与实际持有的数据进行计算。如果想要加到spatialbase中需要进行重构，让spatialbase持有实际的空间数据。

2024-02-06 11:39 UTC, hanwen-sun commented on src/cypher/filter/filter.h
> +                case FieldType::POINT: {
> 缩进

已修改

2024-02-06 11:40 UTC, hanwen-sun commented on src/cypher/procedure/procedure.cpp
> +        "wrong arguments number");
> 换行？

已修改

2024-02-06 11:43 UTC, hanwen-sun commented on test/test_cypher.cpp
> +         {"return point('0101000020E6100000000000000000F03F0000000000000040') as p3", 1},
> return这种关键字大写吧

已修改

2024-02-06 11:44 UTC, hanwen-sun commented on test/test_cypher.cpp
> +        {"return linestringwkb('01020000000300000000000000000000000000000000"
> pointWKB、linestringwkb这种WKB的大小写应该统一

已修改

2024-02-06 13:35 UTC, hanwen-sun commented on test/test_lgraph_spatial.cpp
> +#include "fma-common/assert.h"
> 用到了么

已删除

2024-02-06 13:35 UTC, hanwen-sun commented on test/test_cypher.cpp
> +     "CALL spatial.distance(p1, p2) YIELD distance RETURN distance > 0", 1},
> 判断distance = 某个值吧，如果double不好处理。可以用 delta x = 3、delta y = 4、distance = 5这种整数解

已添加，但这里只能判断是否返回一个值，不能判断true or false

2024-02-26 07:16 UTC, qishipengqsp commented on include/lgraph/lgraph_spatial.h
> +    double Distance(LineString<SRID_Type>& other);
那就重构时候再说吧

2024-04-23 03:22 UTC, lipanpan03 reviewed
it没过，因为增加了一个distance的procedure，需要在test/integration/test_ha_procedure.py和test/integration/test_procedure.py的test_procedure方法中把原有procedure数量从93变为94

2024-04-24 09:07 UTC, gtahoo approved these changes

2024-04-24 13:14 UTC, merged

2024-04-24 15:01 UTC, ljcui commented
https://neo4j.com/docs/bolt/current/bolt/structure-semantics/#structure-point2d
https://neo4j.com/docs/bolt/current/bolt/structure-semantics/#structure-point3d
bolt 里面是有空间地理类型的，cypher里面的POINT类型的传输应该就是这个。
我们目前的实现在neo4j客户端下能否使用，检查下. @qishipengqsp