support float vector data type in schema and storage
TuGraph-family/tugraph-db pull request #475
Opened 2024-04-18 09:40 UTC by Jant1L

参照schema_test, test_field_data_helper, test_field_extractor, test_data_convert等涉及data_type的测试文件，为float vector数据增添相应的测试代码，为对应函数增添float vector的处理逻辑。
在python_api中添加float vector相关接口

TODO:
为double vector和binary vector留出相应接口
使用cypher创建vertex时，parser能够识别到vector数据并存入
为vector的维度增加限制，以保证一致性

2024-04-18 09:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/TuGraph-family/tugraph-db?pullRequest=475) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/TuGraph-family/tugraph-db?pullRequest=475) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/TuGraph-family/tugraph-db?pullRequest=475) it.</sub>

2024-04-19 06:46 UTC, Jant1L commented on test/test_field_extractor.cpp
> +        UT_EXPECT_TRUE(FieldData(fe.GetConstRef(v).AsType<T>()) == fd_ok);
@qishipengqsp

2024-04-19 06:46 UTC, Jant1L commented on test/test_field_extractor.cpp
> +        UT_EXPECT_EQ(UT_FMT("{}", parsed), fe.FieldToString(v));
@qishipengqsp

2024-05-27 07:29 UTC, qishipengqsp requested changes

2024-05-27 07:29 UTC, qishipengqsp commented on src/core/schema.cpp
> +}  // namespace lgraph
按照ci报错，这里需要一个换行符

2024-06-27 08:03 UTC, qishipengqsp requested changes

2024-06-27 08:03 UTC, qishipengqsp commented on test/test_field_extractor.cpp
> +            FieldType::FLOAT_VECTOR, value_tmp, "1.111000,2.111000,3.111000,4.111000,5.111000",
.6 precision?

2024-06-27 08:03 UTC, qishipengqsp commented on test/test_field_extractor.cpp
> +            FieldType::FLOAT_VECTOR, value_tmp, "1.111000,2.111000,3.111000,4.111000,5.111000",
.6 precision?

2024-07-04 11:45 UTC, qishipengqsp requested changes

2024-07-04 11:45 UTC, qishipengqsp commented on src/core/field_data_helper.h
> +    throw std::runtime_error("you cannot compare vectors");
remove you

2024-07-04 11:45 UTC, qishipengqsp commented on src/core/field_data_helper.h
> +    false,  // double vector
add double vector later when you try to implement it

2024-07-04 11:45 UTC, qishipengqsp commented on src/import/jsonlines_parser.h
> +                    throw std::runtime_error("do not support VECTOR type now!");
VECTOR -> vector, be careful about the Caption case

2024-07-04 11:55 UTC, qishipengqsp requested changes

2024-07-04 11:55 UTC, qishipengqsp commented on src/core/field_data_helper.h
> +inline size_t ParseStringIntoFieldData<FieldType::FLOAT_VECTOR>(const char* beg, const char* end,
add some unit test cases

2024-07-04 11:55 UTC, qishipengqsp commented on src/core/field_data_helper.h
> +inline bool ParseStringIntoStorageType<FieldType::FLOAT_VECTOR>
add some ut cases

2024-07-07 15:58 UTC, qishipengqsp approved these changes

2024-07-07 15:58 UTC, merged