support vector index
TuGraph-family/tugraph-db pull request #602
Opened 2024-07-19 03:33 UTC by Jant1L

Support create vector index and query similarity

example：
- CALL vector.AddVectorIndex('person', 'vector', 'IVF_FLAT', 4, 'L2' ,10);
- CALL vector.DeleteVectorIndex('person', 'vector', 'IVF_FLAT', 4, 'L2');
- CALL vector.ShowVectorIndex();
- CALL vector.VectorIndexQuery('person', 'vector', [1,2,3,4], 4, 5);

What it support now：
FAISS IVF_FLAT

TODO:
support more vector index algorithm and library

2024-07-19 03:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/TuGraph-family/tugraph-db?pullRequest=602) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/TuGraph-family/tugraph-db?pullRequest=602) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: Jant1L<br/>:x: PPPoint-t<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/TuGraph-family/tugraph-db?pullRequest=602) it.</sub>

2024-07-19 03:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/TuGraph-family/tugraph-db?pullRequest=602) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/TuGraph-family/tugraph-db?pullRequest=602) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: Jant1L<br/>:x: PPPoint-t<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/TuGraph-family/tugraph-db?pullRequest=602) it.</sub>

2024-07-19 03:35 UTC, Jant1L commented on src/cypher/procedure/procedure.cpp
> +                auto kv_iter = schema->GetPropertyTable().GetIterator(txn.GetTxn());
@qishipengqsp

2024-07-19 03:36 UTC, Jant1L commented on src/core/lightning_graph.cpp
> +        if (schema->DetachProperty()) {
@qishipengqsp

2024-07-22 03:17 UTC, qishipengqsp requested changes

2024-07-22 03:17 UTC, qishipengqsp commented on docs/en-US/source/2.introduction/4.schema.md
> +| FLOAT_VECTOR |                 |                     | The dynamic vector containing 32-bit float numbers |
`dynamic` means?

2024-07-22 03:17 UTC, qishipengqsp commented on include/fma-common/string_util.h
> +inline std::string ToString(std::vector<float> fv) {
Has seen this before? in the last PR?

2024-07-24 08:16 UTC, qishipengqsp commented on src/core/vector_index_layer.h
> +   VectorIndexManager vector_index_manager_;
why VectorIndex holds vectorIndexManager

2024-07-26 07:55 UTC, closed without merging