Column record
TuGraph-family/tugraph-db pull request #683
Opened 2024-09-28 01:23 UTC by Myrrolinz

Designed another record structure according to record's orginal functionality, making it support newly added int vector and string vector.

2024-10-15 03:49 UTC, zhjwpku requested changes

2024-10-15 03:49 UTC, zhjwpku commented on src/cypher/resultset/record.h
> +    void Print() const {
overload operator<< ?

2024-10-15 03:49 UTC, zhjwpku commented on src/cypher/resultset/record.h
> +                                    j[column_name] = column_vector->GetValue<float>(column_pos);
这里类似

2024-10-15 03:49 UTC, zhjwpku commented on src/cypher/resultset/record.h
> +            PrintColumnData<float>(column_name, column);
这里只凭 element_size 来判断打印类型感觉不太对，float 类型会调用 PrintColumnData<int32_t>(column_name, column)？

2024-10-17 00:15 UTC, Myrrolinz commented on src/cypher/resultset/record.h
> +            PrintColumnData<float>(column_name, column);
是的，我在后续写SIMD支持的时候才发现有这个问题，目前也没想好怎么改，您对此有建议吗？

2024-10-17 02:19 UTC, zhjwpku commented on src/cypher/resultset/record.h
> +            PrintColumnData<float>(column_name, column);
> 是的，我在后续写SIMD支持的时候才发现有这个问题，目前也没想好怎么改，您对此有建议吗？

在 ColumnVector 类增加一个 FieldType 字段？不确定，你可以再问下延楠

2024-10-17 05:22 UTC, yannan-wyn commented on src/cypher/resultset/record.h
> +    void AppendToEnd(const DataChunk& source_record) {
方法名叫Append就足够

2024-10-17 05:22 UTC, yannan-wyn commented on src/cypher/resultset/record.h
> +                columnar_data_[column_name] = std::make_unique<ColumnVector>(*src_vector);
std::make_unique<ColumnVector>(*src_vector);
这一步是拷贝构造 && 深拷贝吗

2024-10-17 05:22 UTC, yannan-wyn commented on src/cypher/resultset/record.h
> +    std::unordered_map<std::string, std::vector<uint32_t>> property_vids_;
这里似乎不对吧

点的vid应该对所有属性都是一样的；
而且用ColumnVector保存也因该是OK的。

2024-10-17 05:22 UTC, yannan-wyn commented on src/cypher/resultset/record.h
> +    std::unordered_map<std::string, uint32_t> property_positions_;
property_positions_ 是想记录一共有多少属性？
或者说有多少行？

ColumnVector 应该有类似的方法可以拿到吧，没必要单独存放一个计数器

2024-10-17 05:22 UTC, yannan-wyn commented on src/cypher/resultset/record.h
> +        std::set<uint32_t> sorted_vids;
这个方法实际上仅仅是做了limit？
结合上面的comments， 我认为点的vid对所有属性都是一样的

所以是不是直接根据 usable_r 就可以丢弃过多的属性/vid？

2024-10-21 00:53 UTC, Myrrolinz commented on src/cypher/resultset/record.h
> +                columnar_data_[column_name] = std::make_unique<ColumnVector>(*src_vector);
是的，这里是深拷贝

2024-10-22 03:57 UTC, Myrrolinz commented on src/cypher/resultset/record.h
> +    void AppendToEnd(const DataChunk& source_record) {
已修改

2024-10-22 03:57 UTC, Myrrolinz commented on src/cypher/resultset/record.h
> +            PrintColumnData<float>(column_name, column);
已增加FieldType

2024-10-22 03:58 UTC, Myrrolinz commented on src/cypher/resultset/record.h
> +    std::unordered_map<std::string, std::vector<uint32_t>> property_vids_;
将在下一个版本进一步修改列存数据结构

2024-10-22 04:04 UTC, Myrrolinz commented on src/cypher/resultset/record.h
> +    std::unordered_map<std::string, uint32_t> property_positions_;
property_positions_是记录当前vector数据的长度，这里记录的是非null值，而ColumnVector里的capacity记录的是vector的整体，包括null值。将会再下一个版本进一步修改。

2024-10-22 04:05 UTC, Myrrolinz commented on src/cypher/resultset/record.h
> +        std::set<uint32_t> sorted_vids;
当前的数据是紧密存储的，数据的各个属性与vid并不对齐。将在今后实施对齐。

2024-10-22 13:35 UTC, yannan-wyn approved these changes

2024-10-29 06:53 UTC, zhjwpku approved these changes

2024-10-29 06:53 UTC, merged